FROM ubuntu:23.04

RUN set -ex \
    && sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list

RUN apt-get update \
    && apt-get install git bc bison flex libssl-dev make libc6-dev libncurses5-dev crossbuild-essential-armhf crossbuild-essential-arm64 -y \
    && apt-get clean \
    && rm -rf /tmp/* /var/tmp/*

CMD /bin/bash
