version: '3.8'

services:
  rpi-builder:
    build: 
      dockerfile: ./Dockerfile
    container_name: rpi-builder
    volumes:
      # Create a volume locally to store raspberry linux kernel
      # mkdir -p ./src
      - ./src:/src
    stdin_open: true
    tty: true